Commenting AudioContext from ionic-audio-web-track.ts
AOT failed to build because it cannot find the reference of AudioContext

```
Failed on type
{"filePath":"/Users/faizanhasan/app/v2/node_modules/ionic-audio/dist/ion
ic-audio-web-track.ts","name":"WebAudioTrack","members":[]} with error
Error: Error encountered resolving symbol values statically. Could not
resolve type AudioContext (position 26:105 in the original .ts file),
resolving symbol WebAudioTrack in
/Users/faizanhasan/app/v2/node_modules/ionic-audio/dist/ionic-audio-web-
track.ts
build prod failed: Error encountered resolving symbol values
statically. Could not resolve type AudioContext
            (position 26:105 in the original .ts file), resolving
symbol WebAudioTrack in

/Users/faizanhasan/app/v2/node_modules/ionic-audio/dist/ionic-audio-web-
track.ts
ionic-app-script task: "build"
Error: Error encountered resolving symbol values statically. Could not
resolve type AudioContext (position
            26:105 in the original .ts file), resolving symbol
WebAudioTrack in

/Users/faizanhasan/app/v2/node_modules/ionic-audio/dist/ionic-audio-web-
track.ts
Error: Error encountered resolving symbol values statically. Could not
resolve type AudioContext (position 26:105 in the original .ts file),
resolving symbol WebAudioTrack in
/Users/faizanhasan/app/v2/node_modules/ionic-audio/dist/ionic-audio-web-
track.ts
```